### ISSUE TITLE
When the song is found but there is no lyric, you get the hit anyway

### ISSUE THREAD

**Issue by yulbeast** [LudySu/Synology-LrcPlugin#1]
I try to get lyrics from audio station, so I go to the song info, lyrics tab and press search the internet.
Then I get some results, but I select one of them and nothing happens.
I went to the chinese music.163.com site , repeated the search there, and found that the song is in the database, but they have no lyrics for it.

Shouldn't be the result dismissed if there are no lyrics for the song?

Thanks for the plugin

**Comment by LudySu** [comment]
Thanks for reporting. Actually they are 2 separate steps (also 2 network requests):

1. Search according to the title & artist, get a list of matching songs
2. Download the lyric of the song you select

So to eliminate the songs that don't have a lyric you have to do the second step too, because the results in the first step don't have a flag to indicate whether they have lyric. If there were 20 songs found in the first step, apart from the 1 search request, you would have to send 20 more network requests.

Given this situation, I didn't implement this feature.

**Comment by yulbeast** [comment]
ok, it's not big deal.
It's just the audio station interface doesn't show any message, so you don't know where the problem is.
